name: Deploy to FTP

on:
  push:
    branches:
      - panda  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies and build Next.js app
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          yarn install  # Install project dependencies
          touch .env
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
          echo PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }} >> .env
          yarn build:payload && yarn build:server && yarn copyfiles && yarn build:next

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # This points to the build output directory of your Next.js app
          server-dir: /
          protocol: ftps
          timeout: 300000000  # Set a longer timeout value in milliseconds (here, 2 minutes)
        