name: Deploy to FTP

on:
  push:
    branches:
      - master  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build Next.js app
        run: |
          yarn install  # Install project dependencies
          touch .env.local
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          yarn build:next
          yarn build:payload
          yarn build:server
          yarn copyfiles 

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # This points to the build output directory of your Next.js app
          server-dir: /
          protocol: ftps
          timeout: 300000  # Set a longer timeout value in milliseconds (here, 2 minutes)